### ISSUE TITLE
error opening genome table

### ISSUE THREAD

**Issue by dabitz** [rnakato/DROMPAplus#1]
Hi,

I am trying to use the program, but somehow it is always reporting the error message:

Error: Could nome open genometable.hg19.txt.

I have tried with other samples and get the same error. Could you help me with this issue? 
I am using it with singularity.
Best
André

**Comment by rnakato** [comment]
DROMPAplus requires a genome-table file as input. "genometable.hg19.txt" is available in `data/genometable/` directory. Please download and use it.

**Comment by dabitz** [comment]
This is what I am doing it already, but somehow the program is not recognizing it...
