### ISSUE TITLE
conda package

### ISSUE THREAD

**Issue by darked89** [rnakato/DROMPAplus#10]
Hello,

I am trying to install DROMPAplus on a fairly restricted HPC system (no Singularity, Centos 7, etc.). I attempted to build your package using conda env with the required libraries/gcc/cmake etc. installed, but the build still fails at the cmake stage:

```
CMake Error at 
/path/to/.conda/envs/drompa_plus/share/cmake-3.22/Modules/CMakeDetermineCCompiler.cmake:226
(configure_file):     No such file or directory
Call Stack (most recent call first):
CMakeLists.txt:7 (project)  
```

Debugging some slightly non-conventional setup may be more tricky than trying to create a proper conda package.
Do you plan to package DROMPAplus using conda?

Many thanks for your help

Darek Kedra

**edit**: formatting

**Comment by rnakato** [comment]
Hi Darek,
I'm sorry but I don't have a plan to make the conda package so far. All contributions are welcome.
It would be best if singularity or rootless docker were available in your platform.

Ryu

**Comment by darked89** [comment]
Hello Ryu,

No worries, I fully understand that anybody resources are limited.

Best wishes,

Darek Kedra
