### ISSUE TITLE
Gene Dense text file for ensemble gtf file

### ISSUE THREAD

**Issue by luckysardar** [rnakato/DROMPAplus#11]
Hello,

Thanks for wonderfull tool for chip data I am trying to create gene density text file for GTF file from the ensembl could you please help me to get the output when I am trying getting zero in all the genomic regions and mm10(GRCm38.102) mouse genome gene density data I needed

Thank you

**Comment by rnakato** [comment]
Hi luckysardar,
The `makegenedensity.pl` script in DROMPAplus takes the refFlat-format gene annotation file as input. So please download it from the UCSC genome browser or convert your .gtf file to the refFlat format.

**Comment by luckysardar** [comment]
Hello rnakato,

Thank you for the response I will try and get back to you
