### ISSUE TITLE
command not found: drompa+

### ISSUE THREAD

**Issue by dcheng1** [rnakato/DROMPAplus#2]
I think I successfully installed DROMPAplust using docer. But I still got command not found when I tried to use it.

> DROMPA+ v1.8.1
>     ================
>     For the detailed information on the options for each command, use the -h flag along with the command.
> 
>     Usage: drompa+ <Command> [options]
> 
>     Command:
>         PC_SHARP    Visualization: for sharp mark parameter set
>         PC_BROAD    Visualization: for broad mark parameter set
>         PC_ENRICH   Visualization: ChIP/Input enrichment    
>         GV          Visualization: global-view enrichment   
>         PROFILE     Visualize averaged read density in specified regions
>         MULTICI     Generate matrix of averaged read density in specified BED sites
>         GENWIG      Generate wig data of enrichment or p-value distribution

**Comment by dcheng1** [comment]
I think I found the problem. I need to use 

> docker run -it --rm rnakato/ssp_drompa drompa+

instead of 

> drompa+

**Comment by rnakato** [comment]
Yes. If you have downloaded the docker image by ``docker pull rnakato/ssp_drompa``, drompa+ is only available on the docker and the command like ``docker run -it --rm rnakato/ssp_drompa drompa+`` is needed, as described in the README.
