### ISSUE TITLE
Error: genome table file does not exit

### ISSUE THREAD

**Issue by dcheng1** [rnakato/DROMPAplus#3]
> docker run -it --rm rnakato/ssp_drompa drompa+ PC_BROAD -i m2-22l-n.bw,input.bw,H3K27me3 -o drompa1 -g refFlat.txt --gt /Users/Downloads/genometable.mm10.txt --lpp 2 --showitag 2 --chr 1

The path of genomefile is correct, but still I got the following error:

> Error: genometable file does not exist.
> failed to resize tty, using default size

**Comment by rnakato** [comment]
Maybe you should mount /Users/Downloads/ directory by `-v` option like this:
`docker run -it --rm -v /Users/Downloads/:/Users/Downloads/ rnakato/ssp_drompa drompa+` 

Please see the document of Docker: https://docs.docker.com/storage/volumes/
