### ISSUE TITLE
Error: could nome open genometable.txt

### ISSUE THREAD

**Issue by fffletcher** [rnakato/DROMPAplus#5]
I made a genome table using the makegenometable.pl from your DROMPA3 page as I couldn't find it here. It appears to have given me the right type of file, tab delimited with chromosome name and length, and it is similar to the genome table data you have provided for other organisms. But, when I try to run parse2wig+ I get the error 'could nome open genometable.txt'. I can't figure out what is wrong with my genome table, do you have any ideas for troubleshooting? Thank you.

**Comment by rnakato** [comment]
Dear fffletcher,
- makegenometable.pl is in ``script`` folder.
- Please provide the exact command of parse2wig+. Did you specify the exact file name that you made by the script?

**Comment by fffletcher** [comment]
Hi rnakato, thank you for getting back to me.

I'm sorry, maybe I am missing it, but I cannot seem to find the right script folder. I do see a folder named scripts, but with an icon different from the rest of the folders, this icon has a folder with an arrow, and takes me to a page with one line on it "submodules/SSP/scripts/". If I am in the wrong place could you please tell me where to find makegenometable.pl.

The command I used was
`docker run -it --rm rnakato/ssp_drompa parse2wig+ -i ../ahy.bam -o ahy --gt genometable.txt -n GR`

I installed via Docker. I named the makegenometable.pl output from the DROMPA3 script `genometable.txt`.

Any help would be very much appreciated. Thank you.

**Comment by rnakato** [comment]
Dear fffletcher,
- Sorry it is `scripts` folder, not `script` folder. Actually, it is a symbolic link to `submodules/SSP/scripts/` so you can also access the script with the path `submodules/SSP/scripts/makegenometable.pl`.
- Because you are using the docker command, it is necessary to mount the directory by `-v` option to access the input files as follows:
`docker run -it --rm -v $(pwd):/mnt rnakato/ssp_drompa parse2wig+ -i /mnt/ahy.bam -o ahy --gt /mnt/genometable.txt -n GR`
  This command mounts the current directory to `/mnt` directory in the container. when you use this command, please move the bam file to the current directory. Please see also the document of Docker: https://docs.docker.com/storage/volumes/

**Comment by fffletcher** [comment]
Hi thank you for this, the command seem to be working now. I am however having an issue with writing the output files to the host directory. 

I can find the files in the Docker container if it take out the `-rm` from the command you've given, which allows me to see the container contents, find the `parse2wig+dir` and the files inside.

Do you have any idea what the issue is here? 

Thank you for all your help with this!

**Comment by rnakato** [comment]
You can use `--odir` option to change the path of the output directory:
`docker run -it --rm -v $(pwd):/mnt rnakato/ssp_drompa parse2wig+ -i /mnt/ahy.bam -o ahy --odir /mnt/parse2wigdir+ --gt /mnt/genometable.txt -n GR`
I hope this command will generate the output data you want :)

**Comment by fffletcher** [comment]
Hi, thank you for this. The command you gave works perfectly for `parse2wig+`

But now I am having the same issue with the `drompa+ PC_SHARP` command. I cannot get the files to write to the host directory, I cannot find an option in the `--help` to specify the output directory for the files, and I can't seem to use the work around I described before by actually pulling the files out of the Docker container.

Would you be able to help with this?

Thank you!

**Comment by rnakato** [comment]
Dear fffletcher,

You can specify the output filename by `-o`.

`docker run -it --rm -v $(pwd):/mnt rnakato/ssp_drompa drompa+ PC_SHARP -o /mnt/drompa --gt /mnt/genometable.txt`

**Comment by fffletcher** [comment]
This is my command `docker run -it --rm -v $(pwd):/mnt rnakato/ssp_drompa drompa+ PC_SHARP -i /mnt/ahy.100.bw -o /mnt/drompa1 --gftype 1 -g /mnt/GCF_000182965.3_ASM18296v3_genomic.gtf --gt /mnt/genometable.txt --chr NC_032089.1 ` 

I am not getting any error when I execute, but it is not creating any files in my working directory. Where should these files be found?

**Comment by rnakato** [comment]
Possibly you specified a chromosome name that is not in your genometable file with `--chr` option. Please try to remove `--chr NC_032089.1`.
