### ISSUE TITLE
Why reads in peaks and FRiP are zero?

### ISSUE THREAD

**Issue by CTLife** [rnakato/DROMPAplus#7]
Hi,
I am sure that reads in peaks and FRiP should be normal for my data.
But they are always 0 by DROMPAplus.
Is it a bug?
Thanks in advance.

**Comment by rnakato** [comment]
I'm so sorry that I didn't realize your issue for a long time. 
Thank you for reporting the bug in the FRiP calculation. I've fixed the bug in version 1.13.0.
