### ISSUE TITLE
terminate called after throwing an instance of 'std::out_of_range'   what():  map::at Aborted (core dumped)

### ISSUE THREAD

**Issue by varamhcu** [rnakato/DROMPAplus#8]
Dear rnakato,

Thank you for the amazing program. I am trying to apply the alignment files generated with the bowtie2 program. The reference used here is Oryzasataiva (MSU-TIGR v7). 
I used the below command to generate genometable.txt  for the Osativa reference genome.

makegenometable.pl ../MSU/v7/all.con > MSUv7.genometable.txt

## Successfully generated custom genometable.txt for Oryzasativa genome using makegenometable.pl program in the scripts folder.

Then I went on to perform the next step. This resulted out an error. 
$ parse2wig+ -i IP_B5_R1_sorted_unique.bam -o IP_B5_SU --gt MSUv7.genometable.txt -p 5
## output 
======================================
parse2wig+ version 1.14.0

Input file: IP_B5_R1_sorted_unique.bam
Output prefix: parse2wigdir+/IP_B5_SU
Output format: BIGWIG
Binsize: 100 bp
Genome-table file: MSUv7.genometable.txt
Single-end mode: fragment length will be estimated by strand-shift profile
PCR bias filtering: ON
	10000000 reads used for library complexity

Total read normalization: NONE
Number of threads: 5
======================================
Parsing IP_B5_R1_sorted_unique.bam...
Input format: BAM
mapped reads: 10478968	+ reads: 5234313	- reads: 5244655
duplicated reads: 0
Failed quality reads: 0
unmapped reads: 0
Checking redundant reads: redundancy threshold 1
done.
Making Jaccard index profile...Chr1..Chr3..Chr6..Chr9..Chr12..Chr10..Chr7..ChrUn..ChrSy..Chr4..Chr11..Chr2..Chr8..Chr5..terminate called after throwing an instance of 'std::out_of_range'
  what():  map::at
Aborted (core dumped)

Please help me understand the above error. Let me know if there are any errors in my approach 

FYI. The above approach worked with DROMPA (2018 program). 

Sincerely

**Comment by rnakato** [comment]
Hi varamhcu,
Thank you for using DROMPAplus. I'm sorry for your inconvenience.
Though I didn't test DROMPAplus using O. Sativa, I found that parse2wig+ v1.14.0 does not work when the chromosome name starts with "Chr" instead of "chr". I fixed the bug and update DROMPAplus to v1.14.1, so could you try it?

**Comment by SabinaMT** [comment]
Dear rnakato,

I receive the same error when I tried to run ssp.

docker run -it --rm -v /data3/sabina/methylome_pangenome/drompaplus:/mnt rnakato/ssp_drompa ssp -i /mnt/bam/H3K4me2_UR95.nodup.bam -o H3K4me2_UR95 --odir /mnt/ssp --gt /mnt/genometable_ssp/output/UR95.genomefile  --pair  -p 8 --ng_from 10000 --ng_to 50000 --ng_step 500 --num4ssp 2000000



SSP version 1.2.5 

Input file: /mnt/bam/H3K4me2_UR95.nodup.bam
Output prefix: /mnt/ssp/H3K4me2_UR95
Genome-table file: /mnt/genometable/UR95.genomefile
Paired-end mode: Maximum fragment length: 500
PCR bias filtering: ON
        10000000 reads used for library complexity
SSP background region: [10000,50000], step 500
Read number for SSP: 5000000
Number of threads: 8
======================================
Parsing /mnt/bam/H3K4me2_UR95.nodup.bam...
Input format: BAM
mapped reads: 5371994   unmapped reads: 31490
matched reads: 5371502  matched proper reads: 5045590   unmatched reads: 492
properpair: 2522795     + pairs: 1260582        - pairs: 1262213
duplicated reads: 0
Falied quality reads: 0
Checking redundant reads: redundancy threshold 1
Warning: number of reads (2522771) is < 10 million.
done.
Making Jaccard index profile...UR95.chr_1..UR95.chr_2..UR95.chr_4..UR95.chr_6..UR95.chr_8..UR95.chr_11..UR95.chr_16..UR95.chr_17..UR95.chr_12..UR95.chr_19..UR95.chr_9..UR95.chr_7..UR95.chr_20..UR95.chr_5..UR95.chr_13..UR95.chr_3..UR95.chr_21..UR95.chr_10..UR95.chr_14..terminate called after throwing an instance of 'std::out_of_range'
  what():  map::at
reading genome_table file..

Is there a fix for ssp too? Besides changing chr names? 
 
Thank you.

**Comment by rnakato** [comment]
Dear SabinaMT,

I'm sorry for my late reply. Yes, this is an issue for both DROMPA+ and SSP. Because SSP only considers autosomes, i.e. 'chrN', where N is a numeric number, in the genome_table file, an error occurs if all chromosome names do not start with 'chr'.
To allow for such a case, I've updated SSP (v1.3.0) and DROMPA+ (v1.18.0) and added a new option `--include_allchr`. Please update the docker image in your environment and use the `--include_allchr` option.
Please let me know if there are any other problems.

**Comment by SabinaMT** [comment]
Dear rnakato,

The updated version worked perfectly. Thank you very much!
