### ISSUE TITLE
Error during pdf creation

### ISSUE THREAD

**Issue by nepsygirl** [rnakato/DROMPAplus#9]
Hi rnakato,

I am having some issue during pdf creation. Somehow the pdf creation is not functioning due to output error? So far syntax look ok, but what do i need to specify?

I have following error:

[nepsygirl@localhost Dokumente]$ drompa+ PC_SHARP \ -i $dir/GSM3752858_0-7A-H3K27ac.100.bw ,GSM3752858_0-7A-H3K27ac\ -i $dir/GSM3752867_AD-2A-H3K27ac.100.bw,GSM3752867_AD-2A-H3K27ac\ -i $dir/GSM3752845_Y-15T-H3K27ac.100.bw, GSM3752845_Y-15T-H3K27ac\ -o drompa1 -g refFlat.txt --gt genometable.hg19.txt \ --lpp 2 --showitag 2 \ --chr 1
Error: specify --output option.

Thank you

**Comment by rnakato** [comment]
Hi nepsygirl,
Did you add the backslashes (\\) without line break? What if you remove the backslashes?
In addition, your sample lines (`-i` option) have spaces before and after "," , and the sample labels look specified at the "input" position. Try to change them like this: `-i $dir/GSM3752858_0-7A-H3K27ac.100.bw,,GSM3752858_0-7A-H3K27ac`

**Comment by nepsygirl** [comment]
Hi rnakato,

Thank You for the comment, may be i was doing something wrong. So I tried your tutorial first, downloaded all files and tried to create pdf. So far I am unable to create the file.

`(base) [root@localhost Probe]#  drompa+ PC_SHARP \
> -i $dir/H3K4me3.100.bw, $dir/Input.100.bw, H3K4me3 \
> -i $dir/H3K27me3.100.bw, $dir/Input.100.bw, H3K27me3 \
> -i $dir/H3K36me3.100.bw, $dir/Input.100.bw, H3K36me3 \
> -o pdf1 -g $gene --gt $gt \
> --lpp 2 --showitag 2 \
> --chr 1
Segmentation fault (Speicherabzug geschrieben)`

(base) [root@localhost Probe]#  drompa+ PC_SHARP -i $dir/H3K4me3.100.bw, $dir/Input.100.bw, H3K4me3 -i $dir/H3K27me3.100.bw, $dir/Input.100.bw, H3K27me3 -i $dir/H3K36me3.100.bw, $dir/Input.100.bw, H3K36me3 -o pdf1 -g $gene --gt $gt --lpp 2 --showitag 2 --chr 1
Segmentation fault (Speicherabzug geschrieben)

` 

> (base) [root@localhost Probe]# drompa+ PC_SHARP \

> -i $dir/H3K4me3.100.bw, $dir/Input.100.bw, H3K4me3\
> -i $dir/H3K27me3.100.bw, $dir/Input.100.bw, H3K27me3\
> -i $dir/H3K36me3.100.bw, $dir/Input.100.bw, H3K36me3\
> -o pdf1 -g $gene --gt $gt\
> --lpp 2 --showitag 2\
> --chr 1
the argument ('2--chr') for option '--showitag' is invalid`

For the top one I added as you have it in tutorial, problem was segmentation fault, didn't understand what that was, couldn't solve it, I tried in root too :\, the lower one I tried to remove spaces before '\' which results in syntax error. 

I think the top one is some how correct but cannot find how to solve this problem. 
Please let know if you have some suggestions.

Thanks a lot

**Comment by nepsygirl** [comment]
Hi rnakato,

Please Reply!

**Comment by rnakato** [comment]
Why do you modify the commnad? Please try:

```
drompa+ PC_SHARP \
         -i $dir/H3K4me3.100.bw,$dir/Input.100.bw,H3K4me3 \
         -i $dir/H3K27me3.100.bw,$dir/Input.100.bw,H3K27me3 \
         -i $dir/H3K36me3.100.bw,$dir/Input.100.bw,H3K36me3 \
         -o drompa1 -g refFlat.txt --gt genometable.txt \
         --lpp 2 --showitag 2 --chr 1
```
